export default [
    {
        id: 1,
        name: 'Jeep',
        url: 'https://www.jeep.com/',
        image: './images/pexels-aaron-curtis-119435.jpg',
        year: 2019,
        description: 'Jeep is a brand of American automobiles that is a division of FCA US LLC (formerly Chrysler Group, LLC), a wholly owned subsidiary of the Italian-American corporation Fiat Chrysler Automobiles. Jeep has been a part of Chrysler since 1987, when Chrysler acquired the Jeep brand, along with remaining assets, from its previous owner: American Motors Corporation (AMC).',
        engine: 'V8',
        maxSpeed: 200,
        tank: 60,
    },
    {
        id: 2,
        name: 'Dodge',
        url: 'https://www.dodge.com/',
        image: './images/pexels-garvin-st-villier-3311574.jpg',
        year: 2019,
        description: 'Dodge is an American brand of automobiles, minivans, and sport utility vehicles manufactured by FCA US LLC (formerly known as Chrysler Group LLC), based in Auburn Hills, Michigan. Dodge vehicles currently include the lower-priced badge variants of Chrysler-badged vehicles as well as performance cars, though for much of its existence Dodge was Chrysler\'s mid-priced brand above Plymouth.',
        engine: 'V6',
        maxSpeed: 180,
        tank: 50,
    },
    {
        id: 3,
        name: 'Lada',
        url: 'https://en.wikipedia.org/wiki/Lada',
        image: './images/pexels-johnmark-smith-253096.jpg',
        year: 1997,
        description: 'AvtoVAZ (Russian: АвтоВАЗ, IPA: [ɐvˈtəvɐz]) is a Russian automobile manufacturer headquartered in Togliatti, Samara Oblast, Russia. It is a subsidiary of the French automobile manufacturer Groupe Renault. AvtoVAZ is the largest automobile manufacturer in Russia and the Commonwealth of Independent States. It is the only Russian automobile manufacturer to have survived the collapse of the Soviet Union.',
        engine: 'V4',
        maxSpeed: 140,
        tank: 40,
    },
    {
        id: 4,
        name: 'Mercedes',
        url: 'https://www.mercedes-benz.com/en/',
        image: './images/pexels-mike-b-112460.jpg',
        year: 2017,
        description: 'Mercedes-Benz is a German global automobile marque and a division of Daimler AG. Mercedes-Benz is known for luxury vehicles, buses, coaches, and lorries. The headquarters is in Stuttgart, Baden-Württemberg. The name first appeared in 1926 under Daimler-Benz. In 2018, Mercedes-Benz was the biggest selling premium vehicle brand in the world, having sold 2.31 million passenger cars.',
        engine: 'V8',
        maxSpeed: 220,
        tank: 60,
    },
    {
        id: 5,
        name: 'BMW',
        url: 'https://www.bmw.com/en/index.html',
        image: './images/pexels-mike-b-170811.jpg',
        year: 2018,
        description: 'Bayerische Motoren Werke AG, commonly known as BMW (German: [ˈbeːˈʔɛmˈveː]), is a German multinational company which produces luxury vehicles and motorcycles. The company was founded in 1916 and has its headquarters in Munich, Bavaria. BMW produces motorcycles under BMW Motorrad. In 2012, the BMW Group produced 1,845,186 automobiles and 117,109 motorcycles across all its brands. BMW is part of the "German Big 3" luxury automakers, along with Audi and Mercedes-Benz, which are the three best-selling luxury automakers in the world.',
        engine: 'V6',
        maxSpeed: 200,
        tank: 50,
    },
    {
        id: 6,
        name: 'Audi',
        url: 'https://www.audi.com/en.html',
        image: './images/pexels-mike-b-1035108.jpg',
        year: 2016,
        description: 'Audi AG is a German automobile manufacturer that designs, engineers, produces, markets and distributes luxury vehicles. Audi oversees worldwide operations from its headquarters in Ingolstadt, Bavaria, Germany. Audi-branded vehicles are produced in nine production facilities worldwide. The origins of the company are complex, going back to the early 20th century and the initial enterprises (Horch and the Audiwerke) which would eventually be purchased by the Audi AG of today.',
        engine: 'V6',
        maxSpeed: 200,
        tank: 50,
    },
    {
        id: 7,
        name: 'Mercedes',
        url: 'https://www.mercedes-benz.com/en/',
        image: './images/pexels-mike-b-2365572.jpg',
        year: 2021,
        description: 'Mercedes-Benz is a German global automobile marque and a division of Daimler AG. Mercedes-Benz is known for luxury vehicles, buses, coaches, and lorries. The headquarters is in Stuttgart, Baden-Württemberg. The name first appeared in 1926 under Daimler-Benz. In 2018, Mercedes-Benz was the biggest selling premium vehicle brand in the world, having sold 2.31 million passenger cars.',
        engine: 'V8',
        maxSpeed: 220,
        tank: 60,
    },
    {
        id: 8,
        name: 'Mini Cooper',
        url: 'https://www.mini.com/en_MS/home.html',
        image: './images/pexels-pixabay-35967.jpg',
        year: 2018,
        description: 'The Mini is a small economy car produced by the English-based British Motor Corporation (BMC) and its successors from 1959 until 2000. The original is considered an icon of 1960s British popular culture. Its space-saving transverse engine front-wheel drive layout – allowing 80 percent of the area of the car\'s floorpan to be used for passengers and luggage – influenced a generation of car-makers.',
        engine: 'V4',
        maxSpeed: 180,
        tank: 40,
    },
    {
        id: 9,
        name: 'Hyundai',
        url: 'https://www.hyundai.com/worldwide/en/',
        image: './images/pexels-s-von-hoerst-2920064.jpg',
        year: 2017,
        description: 'Hyundai Motor Company is a South Korean multinational automotive manufacturer headquartered in Seoul. Hyundai Motor Company is the world\'s fifth-largest automaker based on annual vehicle sales. Hyundai Motor Company is the world\'s largest automobile manufacturer by production capacity. Hyundai Motor Company is the world\'s largest exporter of automobiles. Hyundai Motor Company is the world\'s largest automaker by revenue. Hyundai Motor Company is the world\'s largest automaker by sales. Hyundai Motor Company is the world\'s largest automaker by unit sales.',
        engine: 'V6',
        maxSpeed: 200,
        tank: 50,
    },
    {
        id: 10,
        name: 'BMW',
        url: 'https://www.bmw.com/en/index.html',
        image: './images/pexels-torsten-dettlaff-70912.jpg',
        year: 2019,
        description: 'Bayerische Motoren Werke AG, commonly known as BMW (German: [ˈbeːˈʔɛmˈveː]), is a German multinational company which produces luxury vehicles and motorcycles. The company was founded in 1916 and has its headquarters in Munich, Bavaria. BMW produces motorcycles under BMW Motorrad. In 2012, the BMW Group produced 1,845,186 automobiles and 117,109 motorcycles across all its brands. BMW is part of the "German Big 3" luxury automakers, along with Audi and Mercedes-Benz, which are the three best-selling luxury automakers in the world.',
        engine: 'V8',
        maxSpeed: 220,
        tank: 60,
    },
    {
        id: 11,
        name: 'BMW',
        url: 'https://www.bmw.com/en/index.html',
        image: './images/pexels-trace-constant-707046.jpg',
        year: 2015,
        description: 'Bayerische Motoren Werke AG, commonly known as BMW (German: [ˈbeːˈʔɛmˈveː]), is a German multinational company which produces luxury vehicles and motorcycles. The company was founded in 1916 and has its headquarters in Munich, Bavaria. BMW produces motorcycles under BMW Motorrad. In 2012, the BMW Group produced 1,845,186 automobiles and 117,109 motorcycles across all its brands. BMW is part of the "German Big 3" luxury automakers, along with Audi and Mercedes-Benz, which are the three best-selling luxury automakers in the world.',
        engine: 'V6',
        maxSpeed: 200,
        tank: 50,
    }
]